# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5c0909e598067f0376e701295c9a938d"
name = "POS Receipt"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# 注文検索・精算・領収書用
scopes = "read_orders,read_locations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
